security:
    providers:
        in_memory: { memory: null }

    firewalls:
        main:
            lazy: true
            provider: in_memory

    access_control:
        - { path: ^/dashboard, roles: ROLE_USER }
